ignore_nodes: [/rosout, "/*master_client_sync*", "/*master_discovery*", "/*node_manager", /*zeroconf, "/rviz*"]
ignore_topics: ['/rosout', '/rosout_agg']
ignore_services: ['/*get_loggers', '/*set_logger_level']

sync_topics: [/dragonfly*/odom', '/dragonfly*/waypoints', '/dragonfly*/global_waypoints', '/dragonfly*/world_odom', '/dragonfly*/world_apriltag_poses']
sync_services: ['/dragonfly*/mav_services/motors','/dragonfly*/mav_services/takeoff','/dragonfly*/mav_services/land','/dragonfly*/mav_services/goToRelative','/dragonfly*/mav_services/goTo', '/dragonfly*/tag_manager/goTo', '/dragonfly*/tag_manager/goToTimed', '/dragonfly*/tag_search', '/dragonfly*/mav_services/setDesVelInWorldFrame', '/dragonfly*/mav_services/poly_tracker']
