ignore_nodes: [/rosout, "/*master_client_sync* node", "/*master_discovery*", "/*node_manager", /*zeroconf, "/rviz*"]
ignore_topics: ['/rosout', '/rosout_agg', '/tf*']
ignore_services: ['/*get_loggers', '/*set_logger_level']

sync_nodes: ['/csv_to_waypoints']
sync_topics: ['/dragonfly*/waypoints', '/dragonfly*/global_waypoints', '/dragonfly*/world_odom', '/dragonfly*/world_apriltag_poses']
sync_services: ['/dragonfly*/tag']

