ignore_nodes: [/rosout, "/*master_client_sync* node", "/*master_discovery*", "/*node_manager", /*zeroconf, "/rviz*"]
ignore_topics: ['/rosout', '/rosout_agg', '/tf*']
ignore_services: ['/*get_loggers', '/*set_logger_level']

sync_nodes: ['/csv_to_waypoints']
# Has control odom
sync_topics: ['/dragonfly*/position_cmd', '/dragonfly*/odom', '/dragonfly*/quadrotor_ukf/control_odom', '/dragonfly*/quadrotor_ukf/control_odom_throttled', '/dragonfly*/odom_tag', '/dragonfly*/traj', '/swarm_trajs', '/global_semantics', '/dragonfly*/waypoints', '/dragonfly*/semantic_planner_node/global_odom', '/dragonfly*/semantic_planner_node/grid_map/occupancy_inflate', '/dragonfly*/semantic_planner_node/global_list', '/dragonfly*/semantic_planner_node/optimal_list']
# No control odom
# sync_topics: ['/dragonfly*/position_cmd', '/dragonfly*/odom', '/dragonfly*/odom_tag', '/dragonfly*/traj', '/swarm_trajs', '/global_semantics', '/dragonfly*/waypoints', '/dragonfly*/semantic_planner_node/global_odom', '/dragonfly*/semantic_planner_node/grid_map/occupancy_inflate', '/dragonfly*/semantic_planner_node/global_list', '/dragonfly*/semantic_planner_node/optimal_list']
sync_services: ['/dragonfly*/tag']

